### ISSUE TITLE
Issues with ::TopoSort

### ISSUE THREAD

**Issue by mrenvoize** [robkinyon/dbix-class-sims#15]
I'm having issues with the following error which stops my test script dead in it's tracks.

DBIx::Class::Sims::load_sims(): Graph::topological_sort: expected directed acyclic graph, got cyclic, at /usr/local/share/perl/5.14.2/DBIx/Class/TopoSort.pm line 53

Assuming 'cycle' in the TopoSort documentation means a relationship that defines a constraint referencing a column within the same table, i.e an adjacency list, then I'm not sure if this is an issue with DBIx::Class::Sims or my not understanding whether I'm required to add a 'skip' somewhere?

**Comment by robkinyon** [comment]
I'd be happy to get an update for the documentation.

That said, the Sims needs to know which order to create tables. Without this, there's no way to safely auto-generate parent rows (which is the whole point). I am working on a change that will ignore nullable FKs, thereby only requiring you to break cycles that are NOT NULL. Hopefully that would help.
